### ISSUE TITLE
`stylelintLinter.getConfigForFile is not a function`

### ISSUE THREAD

**Issue by AlexWayfer** [alexrudd2/linter-stylelint#162]
I have such error:

![image](https://github.com/alexrudd2/linter-stylelint/assets/6510020/5176311a-7fbb-40b7-9d1f-c6ad151dca10)

Config file:

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

ignorePath: .gitignore

plugins:
  - stylelint-no-unsupported-browser-features

customSyntax: postcss-scss

rules:
  indentation:
    - tab

  max-line-length:
    - 100
    - ignorePattern: /// https?:///

  no-invalid-position-at-import-rule: null

  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - blockless-after-same-name-blockless
      ignoreAtRules:
        - else

  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
        - if
        - else

  declaration-colon-newline-after: null

  function-comma-newline-after: null

  declaration-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - after-declaration

  declaration-block-no-redundant-longhand-properties:
    - true
    - severity: warning

  declaration-colon-space-after:
    - always-single-line

  ## This selectors could not be sorted by specificity:
  # .scrollable { // 0-1-0
  #   table {} // 0-1-1
  # }
  #
  # a + .scrollable, // 0-1-1
  # a + table { // 0-0-2
  # }
  ## Specifity specification: https://www.w3.org/TR/selectors-3/#specificity
  no-descending-specificity: null

  ## https://github.com/stylelint/stylelint/issues/4622
  value-keyword-case:
    - lower
    - ignoreKeywords:
      - BlinkMacSystemFont

  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
      ignore:
        - flexbox
        - css3-cursors
        ## https://github.com/anandthakker/doiuse/issues/70
        - outline
        ## Let's reconcile with IE 11
        - css-appearance


  scss/dollar-variable-empty-line-before:
    - never
    - ignore:
      - after-comment
```
