### ISSUE TITLE
Unable to parse stylelint configuration

### ISSUE THREAD

**Issue by AlexWayfer** [alexrudd2/linter-stylelint#285]
Unexpected token 'export'

![image](https://github.com/user-attachments/assets/70557cb0-ea29-48d1-af63-1789ce12a753)

---

Stylelint config:

```yaml
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - '@stylistic/stylelint-config'

ignorePath: .gitignore

plugins:
  - stylelint-no-unsupported-browser-features

rules:
  '@stylistic/indentation':
    - tab

  '@stylistic/max-line-length':
    - 100
    - ignorePattern: /// https?:///

  ## https://github.com/stylelint-scss/stylelint-scss/issues/538#issuecomment-1234825692
  no-invalid-position-at-import-rule: null

  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - blockless-after-same-name-blockless
      ignoreAtRules:
        - else

  '@stylistic/block-closing-brace-newline-after':
    - always
    - ignoreAtRules:
        - if
        - else

  '@stylistic/declaration-colon-newline-after': null

  '@stylistic/function-comma-newline-after': null

  declaration-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - after-declaration

  declaration-block-no-redundant-longhand-properties:
    - true
    - severity: warning

  '@stylistic/declaration-colon-space-after':
    - always-single-line

  ## This selectors could not be sorted by specificity:
  # .scrollable { // 0-1-0
  #   table {} // 0-1-1
  # }
  #
  # a + .scrollable, // 0-1-1
  # a + table { // 0-0-2
  # }
  ## Specifity specification: https://www.w3.org/TR/selectors-3/#specificity
  no-descending-specificity: null

  ## https://github.com/stylelint/stylelint/issues/4622
  value-keyword-case:
    - lower
    - ignoreKeywords:
      - BlinkMacSystemFont

  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
      ignore:
        - flexbox
        - css3-cursors
        ## https://github.com/anandthakker/doiuse/issues/70
        - outline
        ## Let's reconcile with IE 11
        - css-appearance

overrides:
  - files:
      - '**/*.scss'
    rules:
      plugin/no-unsupported-browser-features:
        - true
        - severity: warning
          ignore:
            - css3-cursors
            - css-nesting
```
